### ISSUE TITLE
Move the mesh data from 0,0

### ISSUE THREAD

**Issue by shimwell** [fusion-energy/openmc_regular_mesh_plotter#2]
This link shows how to move the data 
https://moonbooks.org/Articles/How-to-change-imshow-axis-values-labels-in-matplotlib-/

This will help line up the mesh with the geometry

**Comment by Shimwell** [comment]
It might be required to get the extent from the openm mesh filter

```python
# MeshFilter
mesh = my_tally.filters[2]
mesh.mesh.lower_left
mesh.mesh.upper_right
```
