### ISSUE TITLE
Tally cannot be scaled

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fusion-energy/openmc_regular_mesh_plotter#25]
Currently the only tallies that can be scaled are current, flux, heating, damage-energy.
I would like to scale (n,Xt) with the strenght of my source, but I can't.

the openmc unit is particle/neutron/m3 (i think) and the desired unit is particle/m3/s

The conversion is desired_units = openmc_units * source_strength [n/s]

**Comment by RemDelaporteMathurin** [comment]
I think this stands for all reaction rates, is that right @shimwell ?

**Comment by shimwell** [comment]
plot_regular_mesh_tally takes a source_strength argument.

When combined with required units this should scale the results.

I'm not sure if this works for specific reaction rates, it would depend on the openmc_tally_unit_convertor being able to handle reaction rates.

I think most of the testing is done with flux scaling

I don't have any examples for this but should add one for this

**Comment by RemDelaporteMathurin** [comment]
Yep sounds like the way to go.

In the meantime, is there a simple way to scale the tally by an abitrary float?

Like I just want to do my_tally *= source_strength

**Comment by shimwell** [comment]
there is now an arg called ```scaling_factor```
