### ISSUE TITLE
Remove base_plt

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fusion-energy/openmc_regular_mesh_plotter#34]
https://github.com/fusion-energy/regular_mesh_plotter/blob/c5dbff275d56aaef8ec65fd7d85fc43091e6e8ee/regular_mesh_plotter/core.py#L31-L36

We don't need this as this is redundant and removes flexibility

**Comment by shimwell** [comment]
I think this allows one to combine two plots together, I believe the dagmc-slice-plotter makes use of this.

**Comment by RemDelaporteMathurin** [comment]
this (combining plots together) is natively done in matplotlib, not need to have these lines

**Comment by shimwell** [comment]
I also recall some issue  with plotting two separate plots in one script. They use to be combined unintentionally.

But yes feel free to remove/ refactor

**Comment by shimwell** [comment]
done
